### ISSUE TITLE
pandas 0.24.0 has deprecated pandas.util.decorators

### ISSUE THREAD

**Issue by usul83** [pandas-ml/pandas-ml#117]
See https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#deprecations

This causes the import statement in https://github.com/pandas-ml/pandas-ml/blob/master/pandas_ml/core/frame.py to break.

Looks like just need to change it to 'from pandas.utils'

**Comment by sinhrks** [comment]
closed by #120.
