### ISSUE TITLE
Confusion matrix

### ISSUE THREAD

**Issue by scls19fr** [pandas-ml/pandas-ml#59]
Hello,

You might consider merging code with https://github.com/scls19fr/pandas_confusion

Kind regards

**Comment by sinhrks** [comment]
Thanks for sharing.

How about ``ModelFrame.metrics.confusion_matrix`` to return ``ConfusionMatrix`` instance when your package installed?

https://github.com/sinhrks/pandas-ml/blob/master/pandas_ml/skaccessors/metrics.py#L55

**Comment by scls19fr** [comment]
Yes it could be a good idea because "my" `ConfusionMatrix` have several methods to output metrics (F1 score, sensivity TPR, specificity TNR ... see https://en.wikipedia.org/wiki/Sensitivity_and_specificity )
But an other approach could be to really merged our project to have only one project about Python / Pandas / Machine Learning and a good confusion matrix is part of such a project.

**Comment by sinhrks** [comment]
I'm willing to merge project, and appreciated if you join:)

**Comment by scls19fr** [comment]
Ok. Maybe we should turn to an organization or ask to add this project to pydata organization.

**Comment by sinhrks** [comment]
OK. Because we only have few uses, how about starting from separate org? We can reconsider when we achieve more users.

**Comment by scls19fr** [comment]
Ok. I've accept invite to pandas-ml organization https://github.com/pandas-ml

**Comment by scls19fr** [comment]
Ownership have been transferred from @scls19fr to @pandas-ml organization

https://github.com/pandas-ml/pandas_confusion

**Comment by scls19fr** [comment]
Still need to add `ConfusionMatrix` to `metrics`

**Comment by scls19fr** [comment]
We need to also add doc about `ConfusionMatrix` in `pandas-ml` doc

**Comment by sinhrks** [comment]
Yep, also I'm considering to make ``ConfusionMatrix`` a subclass of ``DataFrame``. It makes filtering / aggregation easier.

**Comment by scls19fr** [comment]
I think this is closed by https://github.com/pandas-ml/pandas-ml/pull/69
@sinhrks ?

**Comment by sinhrks** [comment]
Yeah, thx!
