### ISSUE TITLE
Confusion Matrix no accessible

### ISSUE THREAD

**Issue by mmartinortiz** [pandas-ml/pandas-ml#82]
Hi,

I've been using `confusion_matrix` since it was an independent package. I've installed `pandas_ml` to continue using the package, but it seems that the `setup.py` script does not install the package.

Could it be an issue with the `find_packages` function?

**Comment by scls19fr** [comment]
You can import it using:

    from pandas_ml.confusion_matrix import ConfusionMatrix

**Comment by sinhrks** [comment]
Let's add ``ConfusionMatrix`` to top namespace:)

- https://github.com/pandas-ml/pandas-ml/blob/master/pandas_ml/__init__.py
